import { Platform, StyleSheet } from "react-native";

function shadow(opacity: number, radius: number, elevation: number) {
  return Platform.select({
    ios: {
      shadowColor: "#000",
      shadowOpacity: opacity,
      shadowRadius: radius,
      shadowOffset: { width: 0, height: 8 },
    },
    android: {
      elevation,
    },
    default: {},
  });
}

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#07111f",
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  blobA: {
    position: "absolute",
    top: -70,
    right: -40,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "rgba(45, 212, 191, 0.18)",
  },
  blobB: {
    position: "absolute",
    left: -80,
    top: 180,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "rgba(245, 158, 11, 0.14)",
  },
  chrome: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
    gap: 10,
  },
  kicker: {
    color: "#7dd3fc",
    textTransform: "uppercase",
    letterSpacing: 2,
    fontSize: 11,
    fontWeight: "700",
  },
  title: {
    color: "#f8fafc",
    fontSize: 30,
    lineHeight: 34,
    fontWeight: "800",
    marginTop: 6,
  },
  subtitle: {
    color: "#aac0d8",
    marginTop: 10,
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 340,
  },
  statusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  protocolNav: {
    paddingHorizontal: 14,
    paddingTop: 0,
    paddingBottom: 6,
    gap: 6,
  },
  protocolNavGroup: {
    gap: 4,
  },
  protocolNavGroupTitle: {
    color: "#7dd3fc",
    textTransform: "uppercase",
    letterSpacing: 1.1,
    fontSize: 10,
    fontWeight: "800",
  },
  protocolNavChipRow: {
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  protocolNavChip: {
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
    backgroundColor: "rgba(148, 163, 184, 0.08)",
  },
  protocolNavChipActive: {
    borderColor: "rgba(34, 197, 94, 0.55)",
    backgroundColor: "rgba(4, 120, 87, 0.22)",
  },
  protocolNavChipPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.985 }],
  },
  protocolNavChipText: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "700",
  },
  protocolNavChipTextActive: {
    color: "#f8fafc",
    fontWeight: "800",
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 24,
    gap: 14,
  },
  heroCard: {
    backgroundColor: "#0f172a",
    borderColor: "rgba(148, 163, 184, 0.18)",
    borderWidth: 1,
    borderRadius: 28,
    padding: 18,
    gap: 14,
    ...shadow(0.28, 12, 24),
  },
  heroHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  heroHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  heroStatusWrap: {
    flexShrink: 0,
    alignSelf: "flex-start",
  },
  heroTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  heroText: {
    color: "#94a3b8",
    marginTop: 8,
    lineHeight: 20,
    paddingRight: 8,
  },
  heroActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  primaryButton: {
    backgroundColor: "#22c55e",
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 18,
    minWidth: 104,
  },
  primaryButtonText: {
    color: "#04110a",
    fontWeight: "800",
    textAlign: "center",
  },
  secondaryButton: {
    backgroundColor: "rgba(148, 163, 184, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 18,
  },
  secondaryButtonText: {
    color: "#e2e8f0",
    fontWeight: "700",
  },
  buttonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.985 }],
  },
  pill: {
    backgroundColor: "rgba(148, 163, 184, 0.14)",
    borderColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  pillAccent: {
    backgroundColor: "rgba(14, 165, 233, 0.18)",
  },
  pillSuccess: {
    backgroundColor: "rgba(34, 197, 94, 0.18)",
  },
  pillText: {
    color: "#f8fafc",
    fontWeight: "700",
    fontSize: 12,
  },
  tabBar: {
    flexDirection: "row",
    gap: 8,
    padding: 8,
    borderRadius: 22,
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.12)",
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "transparent",
    alignItems: "center",
  },
  tabButtonActive: {
    backgroundColor: "#f97316",
  },
  tabButtonText: {
    color: "#cbd5e1",
    fontWeight: "700",
    fontSize: 12,
  },
  tabButtonTextActive: {
    color: "#fff7ed",
  },
  sectionPanel: {
    backgroundColor: "#0b1324",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
    padding: 16,
    gap: 16,
    ...shadow(0.22, 10, 22),
  },
  sectionPanelHeader: {
    gap: 4,
  },
  sectionPanelTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  sectionPanelSubtitle: {
    color: "#94a3b8",
    fontSize: 13,
  },
  helperText: {
    color: "#94a3b8",
    lineHeight: 20,
  },
  libraryGrid: {
    gap: 12,
  },
  protocolCard: {
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
    padding: 16,
    gap: 10,
  },
  protocolCardSelected: {
    borderColor: "rgba(34, 197, 94, 0.5)",
    backgroundColor: "rgba(4, 120, 87, 0.16)",
  },
  protocolCardFocused: {
    shadowColor: "#38bdf8",
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  protocolCardPressed: {
    opacity: 0.86,
  },
  protocolCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  protocolTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
    flexShrink: 1,
  },
  protocolDescription: {
    color: "#cbd5e1",
    lineHeight: 20,
  },
  formGrid: {
    gap: 12,
  },
  dualRow: {
    flexDirection: "row",
    gap: 12,
  },
  dualCol: {
    flex: 1,
  },
  fieldWrap: {
    gap: 8,
  },
  fieldLabel: {
    color: "#cbd5e1",
    fontSize: 13,
    fontWeight: "700",
  },
  fieldInput: {
    backgroundColor: "#101a31",
    color: "#f8fafc",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  fieldInputMultiline: {
    textAlignVertical: "top",
    paddingTop: 14,
  },
  selectionChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  selectionChip: {
    backgroundColor: "rgba(14, 165, 233, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(14, 165, 233, 0.22)",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
  },
  selectionChipText: {
    color: "#e0f2fe",
    fontWeight: "700",
    fontSize: 12,
  },
  activeProtocolBlock: {
    gap: 12,
  },
  blockLabel: {
    color: "#7dd3fc",
    textTransform: "uppercase",
    letterSpacing: 1,
    fontSize: 11,
    fontWeight: "800",
  },
  sectionCard: {
    backgroundColor: "rgba(15, 23, 42, 0.78)",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    padding: 14,
    gap: 12,
  },
  obpMobileHintCard: {
    backgroundColor: "rgba(56, 189, 248, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(125, 211, 252, 0.18)",
    borderRadius: 22,
    padding: 14,
    gap: 6,
  },
  obpMobileHintTitle: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "800",
  },
  obpMobileHintText: {
    color: "#cbd5e1",
    lineHeight: 20,
  },
  obpSampleList: {
    gap: 8,
  },
  obpSampleButton: {
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 4,
  },
  obpSampleButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  obpSampleButtonTitle: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "800",
  },
  obpSampleButtonText: {
    color: "#cbd5e1",
    fontSize: 12,
    lineHeight: 18,
  },
  obpFieldList: {
    gap: 10,
  },
  obpFieldRow: {
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    padding: 14,
    gap: 8,
  },
  obpFieldRowFilled: {
    borderColor: "rgba(34, 197, 94, 0.55)",
    backgroundColor: "rgba(4, 120, 87, 0.14)",
  },
  obpFieldRowReadonly: {
    opacity: 0.78,
    borderColor: "rgba(148, 163, 184, 0.1)",
  },
  obpFieldRowPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.99 }],
  },
  obpFieldRowContent: {
    gap: 6,
  },
  obpFieldLabel: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "800",
  },
  obpFieldValue: {
    color: "#cbd5e1",
    lineHeight: 20,
  },
  obpFieldType: {
    color: "#7dd3fc",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
    alignSelf: "flex-end",
  },
  kidneyInlineHeader: {
    marginTop: 8,
    marginBottom: 4,
    paddingTop: 2,
    paddingBottom: 2,
    paddingHorizontal: 2,
    gap: 3,
  },
  kidneyInlineHeaderLabel: {
    color: "#e0f2fe",
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  kidneyInlineHeaderNote: {
    color: "#bfdbfe",
    fontSize: 11,
    lineHeight: 16,
  },
  kidneyPlainSection: {
    gap: 12,
    marginTop: 2,
    marginBottom: 2,
    paddingVertical: 0,
    paddingHorizontal: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  kidneyOrganHeader: {
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  kidneyOrganTitle: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  sectionCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  sectionLabel: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "800",
  },
  sectionDesktopKey: {
    color: "#94a3b8",
    fontSize: 12,
    marginTop: 4,
  },
  emptyState: {
    color: "#94a3b8",
    fontStyle: "italic",
  },
  emptyProtocolState: {
    backgroundColor: "rgba(148, 163, 184, 0.08)",
    borderRadius: 24,
    padding: 16,
    gap: 8,
  },
  emptyProtocolTitle: {
    color: "#f8fafc",
    fontWeight: "800",
    fontSize: 16,
  },
  emptyProtocolText: {
    color: "#94a3b8",
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: "#101a31",
    borderRadius: 24,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
  },
  reviewCard: {
    backgroundColor: "#091324",
    borderRadius: 24,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(96, 165, 250, 0.18)",
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  reviewTitle: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 4,
  },
  reviewList: {
    gap: 10,
  },
  reviewReadyText: {
    color: "#cbd5e1",
    lineHeight: 20,
  },
  reviewIssueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  reviewIssueDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fb7185",
  },
  reviewIssueText: {
    color: "#fecdd3",
    flex: 1,
  },
  saveButton: {
    backgroundColor: "#38bdf8",
  },
  saveButtonDisabled: {
    backgroundColor: "rgba(56, 189, 248, 0.28)",
  },
  printButton: {
    marginTop: 10,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: "#0ea5e9",
    ...shadow(0.22, 10, 18),
  },
  printButtonText: {
    color: "#f8fafc",
    fontWeight: "800",
    fontSize: 15,
  },
  clearButton: {
    marginTop: 10,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: "#ef4444",
    ...shadow(0.22, 10, 18),
  },
  clearButtonText: {
    color: "#fff7f7",
    fontWeight: "800",
    fontSize: 15,
  },
  saveSuccessText: {
    color: "#86efac",
    fontWeight: "700",
    lineHeight: 20,
  },
  reviewHintText: {
    color: "#94a3b8",
    lineHeight: 20,
  },
  inlineStat: {
    gap: 3,
  },
  inlineStatLabel: {
    color: "#7dd3fc",
    textTransform: "uppercase",
    letterSpacing: 1,
    fontSize: 10,
    fontWeight: "800",
  },
  inlineStatValue: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "700",
  },
  summaryList: {
    gap: 10,
  },
  summaryListItem: {
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    borderRadius: 18,
    padding: 12,
    gap: 3,
  },
  summaryListTitle: {
    color: "#f8fafc",
    fontWeight: "800",
  },
  summaryListHint: {
    color: "#94a3b8",
  },
  errorBox: {
    backgroundColor: "rgba(239, 68, 68, 0.16)",
    borderColor: "rgba(239, 68, 68, 0.32)",
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
  },
  errorText: {
    color: "#fecaca",
    fontWeight: "700",
  },
  connectionNotice: {
    marginHorizontal: 16,
    marginBottom: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "rgba(14, 165, 233, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(125, 211, 252, 0.24)",
  },
  connectionNoticeText: {
    color: "#e0f2fe",
    fontWeight: "800",
    textAlign: "center",
  },
  bottomNav: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 14,
    backgroundColor: "rgba(7, 17, 31, 0.94)",
    borderTopWidth: 1,
    borderTopColor: "rgba(148, 163, 184, 0.14)",
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "rgba(148, 163, 184, 0.08)",
  },
  navItemActive: {
    backgroundColor: "#f97316",
  },
  navItemPressed: {
    opacity: 0.86,
  },
  navLabel: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "800",
  },
  navLabelActive: {
    color: "#fff7ed",
  },
  scannerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(2, 6, 23, 0.94)",
    padding: 16,
    gap: 16,
  },
  scannerHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  scannerTitle: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "800",
  },
  scannerSubtitle: {
    color: "#94a3b8",
    marginTop: 6,
    lineHeight: 20,
    maxWidth: 320,
  },
  scannerCloseButton: {
    backgroundColor: "rgba(148, 163, 184, 0.14)",
    borderColor: "rgba(148, 163, 184, 0.22)",
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
  },
  scannerCloseButtonText: {
    color: "#e2e8f0",
    fontWeight: "700",
  },
  scannerCamera: {
    flex: 1,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
  },
  scannerPermissionCard: {
    flex: 1,
    borderRadius: 24,
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 14,
  },
  scannerPermissionTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  scannerPermissionText: {
    color: "#94a3b8",
    lineHeight: 20,
    textAlign: "center",
  },
  scannerPermissionButton: {
    alignSelf: "stretch",
  },
});

export type AppStyles = typeof styles;
