// Frontend/src/types/index.ts
export * from './kidney';
export * from './gallbladder';
export * from './hepat';
export * from './pancreas';
export * from './spleen';
export * from './urinarybladder';
export * from './defaultStates';
export * from './ovary';
export * from './uterus';
export type { OvaryCyst } from './ovary';
export * from "./prostate";
export * from "./testis";
export * from "./thyroid";
export * from "./breast";
export * from "./childDispensary";
export * from "./softTissue";
export * from "./obp";
export * from './kidneyStudy';
export * from './omtFemale';
export * from './omtMale';
export * from './breastStudy';
export * from './scrotum';
export * from './thyroidStudy';
export * from './urinaryBladderStudy';
