// src/types/defaultStates/organs/kidney.ts
import type { KidneyProtocol } from "../../organs/kidney";

export const defaultKidneyState: KidneyProtocol = {
  position: "",  
  positionText: "",  
  length: "",
  width: "",
  thickness: "",
  parenchymaSize: "",
  parenchymaEchogenicity: "",
  parenchymaStructure: "",
  parenchymaConcrements: "не определяются",
  parenchymaConcrementslist: [],
  parenchymaCysts: "не определяются",
  parenchymaCystslist: [],
  parenchymaMultipleCysts: false,
  parenchymaMultipleCystsSize: "",
  parenchymaPathologicalFormations: "не определяются",
  parenchymaPathologicalFormationsText: "",
  pcsSize: "",
  pcsMicroliths: "не определяются",
  pcsMicrolithsSize: "",
  pcsConcrements: "не определяются",
  pcsConcrementslist: [],
  pcsCysts: "не определяются",
  pcsCystslist: [],
  pcsMultipleCysts: false,
  pcsMultipleCystsSize: "",
  pcsPathologicalFormations: "не определяются",
  pcsPathologicalFormationsText: "",
  sinus: "",
  adrenalArea: "",
  adrenalAreaText: "",
  contour: "",
  additional: "",
};
